/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package clubconnect.ui;

import clubconnect.dao.ClubDAO;
import clubconnect.dao.EventDAO;
import clubconnect.models.Club;
import clubconnect.models.Event;
import java.text.SimpleDateFormat;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lisema Mariti
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
         loadApprovedClubs();
         loadEventListings();
    }

    
    private void loadApprovedClubs() {
    // Get the table model from your tblClubListings
    DefaultTableModel model = (DefaultTableModel) tblClubListings.getModel();
    model.setRowCount(0); // clear existing rows

    // Fetch all approved clubs from DAO
    List<Club> clubs = ClubDAO. getApprovedClubs();

    if (clubs.isEmpty()) {
        JOptionPane.showMessageDialog(this, "No approved clubs found.");
        return;
    }

    // Add each club to the table
    for (Club c : clubs) {
        model.addRow(new Object[]{
            c.getClubId(),
            c.getName(),
            c.getDescription(),
            c.getLeaderName(),
            c.getStatus()
        });
    }
}
    private void loadEventListings() {
    DefaultTableModel model = (DefaultTableModel) tblEventListings.getModel();
    model.setRowCount(0); // Clear old data

    List<Event> events = EventDAO.getUpcomingEvents();

    if (events.isEmpty()) {
        JOptionPane.showMessageDialog(this, "No upcoming events found.", "Info", JOptionPane.INFORMATION_MESSAGE);
        return;
    }

    for (Event e : events) {
        model.addRow(new Object[]{
            e.getEventId(),
            e.getName(),
            e.getDescription(),
            e.getClubName(),
            e.getRoomName() != null ? e.getRoomName() : "N/A",
            new SimpleDateFormat("yyyy-MM-dd HH:mm").format(e.getEventDate())
        });
    }
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblClubListings = new javax.swing.JTable();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblEventListings = new javax.swing.JTable();
        btnGetStarted = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblClubListings.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ClubID", "Name", "Description", ""
            }
        ));
        jScrollPane1.setViewportView(tblClubListings);

        jTabbedPane2.addTab("View registered clubs", jScrollPane1);

        jTabbedPane1.addTab("Club Listings", jTabbedPane2);

        tblEventListings.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "EventID", "EventName", "Description", "Club"
            }
        ));
        jScrollPane2.setViewportView(tblEventListings);

        jTabbedPane3.addTab("View Upcoming events", jScrollPane2);

        jTabbedPane1.addTab("Events", jTabbedPane3);

        btnGetStarted.setText("Get started");
        btnGetStarted.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetStartedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 684, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGetStarted)
                .addGap(34, 34, 34))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(btnGetStarted)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGetStartedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetStartedActionPerformed
                                                  
    // Open the login form
    LoginForm loginForm = new LoginForm();
    loginForm.setVisible(true);

    // Close the home page
    this.dispose();

    }//GEN-LAST:event_btnGetStartedActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGetStarted;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTable tblClubListings;
    private javax.swing.JTable tblEventListings;
    // End of variables declaration//GEN-END:variables
}
